#!/bin/sh

# program name: A blog generation script
# 2021 Bryce Vandegrift
# This program is licensed under the GPL V3
# Report bugs to: bpv@disroot.org

name="Bryce Vandegrift"
website="https://brycevandegrift.xyz/"
blog_dir="blog"
blogindex="blog/index.html"
rssindex="rss.xml"
draft_dir=".drafts"

default() {
	if [ -z "$1" ]; then
		help
	else
		echo "ERROR: $1 is not a valid command!"
	fi
}

listDrafts() {
	echo "Printing drafts"
}

delete() {
	echo "Deleting draft"
}

help() {
	cat <<-EOF
Usage:
        sbs [OPERATION] ...
Operations:
        sbs publish
        sbs edit
        sbs help
                Show this text
        sbs version
                Show program version
EOF
}

version() {
	echo "sbs: Static Blogging System V1.0.0"
}

case "$1" in
	edit) shift;	"$@" ;;
	delete|del) shift;	"$@" ;;
	help|--h) shift;	help "$@" ;;
	version|--v) shift;	version "$@" ;;
	*)	default "$@" ;;
esac
exit 0
