#!/bin/sh

# Static Blogging System: A blog generation script
# 2021 Bryce Vandegrift
# This program is licensed under the GPL V3
# Report bugs to: bpv@disroot.org

name="Bryce Vandegrift"
website="https://brycevandegrift.xyz/"
website_dir="/home/bryce/Documents/website"
blog_dir="blog"
blogindex="blog/index.html"
rssindex="rss.xml"
draft_dir=".drafts"
html_css_path="//brycevandegrift.xyz/index.css"
html_icon_path="//brycevandegrift.xyz/p/icon.ico"

default() {
	[ -z "$1" ] && help || echo "ERROR: $1 is not a valid command!" && exit 1
}

listDrafts() {
	echo "Printing drafts"
	case "$(ls "$website_dir/$draft_dir" | wc -l)" in
		0) echo "There are no drafts." && exit 1 ;;
		*) ls -rc "$website_dir/$draft_dir" | nl
		read -rp "Pick a draft to $1: " number ;;
	esac
	choice="$(ls -rc "$website_dir/$draft_dir" | nl | grep -w $number | awk '{print $2}')"
}

new() {
	read -rp "Enter file name: " name
	echo $name | grep -q "\"" && echo "Double quotes are not allowed in file names." && exit 1
	url="$(echo $name | tr -d '[:punct:]' | tr ' ' '-' | tr '[:upper:]' '[:lower:]')"
	( [ -f "$website_dir/$draft_dir/$url.md" ] || [ -f "$website_dir/$blog_dir/$url.html" ] ) && echo "A draft or post already exists under that name!" && exit 1
	$EDITOR "$website_dir/.drafts/$url.md"
}

edit() {
	listDrafts edit "$@"
	$EDITOR "$website_dir/$draft_dir/$choice"
}

publish() {
	listDrafts publish "$@"
	contents=$(pandoc -f markdown -t html "$website_dir/$draft_dir/$choice")
	title=$(echo "$contents" | grep "<h1.*</h1>$" | sed 's/<\/h1>$//g' | sed 's/^<h1\s.*>//g') 
	printf "<!DOCTYPE html>\n<html lang=\"en\" dir=\"ltr\">\n<head>\n<meta charset=\"utf-8\">\n<link rel=\"icon\" href='%s' type=\"image/x-icon\">\n<link rel=\"stylesheet\" href='%s'>\n<title>%s</title>\n</head>\n<body>\n%s\n</body>\n</html>" "$html_icon_path" "$html_css_path" "$title" "$contents"
	printf ""
	printf ""
}

delete() {
	listDrafts delete "$@"
	rm "$website_dir/$draft_dir/$choice"
}

help() {
	cat <<-EOF
Usage:
        sbs [OPERATION] ...
Operations:
        sbs new
        sbs edit
	sbs publish
	sbs delete
        sbs help
                Show this text
        sbs version
                Show program version
EOF
}

version() {
	echo "sbs: Static Blogging System V1.0.0"
}

[ -z "$EDITOR" ] && EDITOR="vi"

case "$1" in
	new) shift;	new "$@" ;;
	edit) shift;	edit "$@" ;;
	publish) shift;		publish "$@" ;;
	delete|del) shift;	delete "$@" ;;
	help|-h) shift;	help "$@" ;;
	version|-v) shift;	version "$@" ;;
	*)	default "$@" ;;
esac
exit 0
